---
- name: Gather system information from localhost
  hosts: localhost
  become: yes
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_result

    - name: Print hostname
      debug:
        msg: "Hostname: {{ hostname_result.stdout }}"

    - name: Get IP addresses
      command: hostname -I
      register: ip_result

    - name: Print IP addresses
      debug:
        msg: "IP addresses: {{ ip_result.stdout }}"

    - name: Get system information
      command: uname -a
      register: uname_result

    - name: Print system information
      debug:
        msg: "System info: {{ uname_result.stdout }}"

    - name: Get OS release info
      command: cat /etc/os-release
      register: os_release_result

    - name: Print OS release info
      debug:
        msg: "OS Release Info: {{ os_release_result.stdout }}"

    - name: Get memory usage
      command: free -h
      register: free_result

    - name: Print memory usage
      debug:
        msg: "Memory usage: {{ free_result.stdout }}"

    - name: Get disk usage
      command: df -h
      register: df_result

    - name: Print disk usage
      debug:
        msg: "Disk usage: {{ df_result.stdout }}"

    - name: Get CPU info
      command: lscpu
      register: lscpu_result

    - name: Print CPU info
      debug:
        msg: "CPU info: {{ lscpu_result.stdout }}"

    - name: Get network configuration
      command: ip a
      register: ip_a_result

    - name: Print network configuration
      debug:
        msg: "Network configuration: {{ ip_a_result.stdout }}"

    - name: Get routing table
      command: ip route
      register: ip_route_result

    - name: Print routing table
      debug:
        msg: "Routing table: {{ ip_route_result.stdout }}"

    - name: Get system uptime
      command: uptime
      register: uptime_result

    - name: Print system uptime
      debug:
        msg: "System uptime: {{ uptime_result.stdout }}"
