---
- name: Test Filesystem Module
  hosts: localhost
  become: yes
  vars:
    vg_name: vg0
    lvs:
      - name: lv_test
        size: 1G
        mount_point: /mnt

  tasks:
    - name: Ensure logical volume is created
      command: "lvcreate -n {{ item.name }} -L {{ item.size }} {{ vg_name }}"
      loop: "{{ lvs }}"
      register: lv_create
      ignore_errors: yes

    - name: Ensure logical volumes are formatted with XFS
      command: "mkfs.xfs /dev/{{ vg_name }}/{{ item.name }}"
      loop: "{{ lvs }}"
      when: lv_create.rc == 0

    - name: Ensure mount point directories exist
      file:
        path: "{{ item.mount_point }}"
        state: directory
      loop: "{{ lvs }}"

    - name: Mount logical volumes
      mount:
        path: "{{ item.mount_point }}"
        src: "/dev/{{ vg_name }}/{{ item.name }}"
        fstype: xfs
        opts: defaults
        state: mounted
      loop: "{{ lvs }}"
      when: lv_create.rc == 0
