---
- name: Setup LVM and mount file systems dynamically
  hosts: localhost
  become: yes
  vars_files:
    - ./var.yaml

  tasks:

    - name: Ensure physical volumes are created
      shell: /usr/sbin/pvcreate -ff {{ item }}
      loop: "{{ pv_devices }}"
      become: yes
      tags: lvm
