---
- name: Setup LVM and mount file systems dynamically
  hosts: localhost
  become: yes
  vars_files:
    - ./var.yaml

  tasks:
    - name: Install LVM2 package
      yum:
        name: lvm2
        state: present

    - name: Ensure physical volumes are created
      lvg:
        pvs: "{{ pv_devices }}"
        vg: "{{ vg_name }}"
      tags: lvm

    - name: Ensure logical volumes are created
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      loop: "{{ lvs }}"
      register: lv_create
      tags: lvm

    - name: Ensure logical volumes are formatted with XFS
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ item.name }}"
      loop: "{{ lvs }}"
      when: lv_create is success
      tags: filesystem

    - name: Ensure mount point directories exist
      file:
        path: "{{ item.mount_point }}"
        state: directory
      loop: "{{ lvs }}"
      tags: mount

    - name: Mount logical volumes
      mount:
        path: "{{ item.mount_point }}"
        src: "/dev/{{ vg_name }}/{{ item.name }}"
        fstype: xfs
        opts: defaults
        state: mounted
      loop: "{{ lvs }}"
      when: lv_create is success
      tags: mount
